---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": schema.yaml
title: Overture Maps Feature Schema
description: >-
  Prototype schema for Overture Maps Foundation map entities as GeoJSON
  schemas.
type: object
unevaluatedProperties: false
allOf:
  - "$ref": https://geojson.org/schema/Feature.json
    "$comment": Every Overture feature IS A GeoJSON feature
oneOf:
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [admins] }
            type: { enum: [locality] }
    then: { "$ref": admins/locality.yaml }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [admins] }
            type: { enum: [administrativeBoundary] }
    then: { "$ref": admins/administrativeBoundary.yaml }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [buildings] }
            type: { enum: [footprint] }
    then: { "$ref": buildings/footprint.yaml }
    else: { propertyNames: false }
  - if:
      description: "# Transportation Connectors"
      properties:
        properties:
          properties:
            theme: { enum: [transportation] }
            type: { enum: [connector] }
    then: { "$ref": transportation/connector.yaml }
    else: { propertyNames: false }
  - if:
      description: "# Transportation Segments"
      properties:
        properties:
          properties:
            theme: { enum: [transportation] }
            type: { enum: [segment] }
    then: { "$ref": transportation/segment.yaml }
    else: { propertyNames: false }
