name: build-documentation

on:
  push:
    branches: [documentation_autobuilding]
  pull_request:
    branches: [dev]

  # Allow running from the actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the schema-wg repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: Install Dependencies
        run: cd docusaurus && npm install
      - name: Build Docusaurus website
        run: cd docusaurus && npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docusaurus/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
